---
- name: Install postgresql
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev

- name: Ensure postgresql homedir
  file:
    path: /home/postgres
    owner: postgres
    group: postgres
    mode: 0755

- name: Ensure postgresql service is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Ensure database
  sudo_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    state: present
  notify: restart postgresql

- name: Ensure database user
  sudo_user: postgres
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    state: present
  notify: restart postgresql

- name: Ensure database role has CREATEDB
  sudo_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    role_attr_flags: CREATEDB
    state: present
  notify: restart postgresql

- name: Ensure postgresql config files
  file:
    src: "etc/postgresql/9.5/main/{{ item }}"
    dest: "/etc/postgresql/9.5/main/{{ item }}"
    owner: postgres
    group: postgres
    mode: 0644
  with_items:
    - postgresql.conf
    - pg_hba.conf

- name: Ensure backups dir
  file:
    path: /home/postgres/backups
    owner: postgres
    group: postgres
    mode: 0755

- name: Ensure pg_backup.config
  template:
    src: home/postgres/backups/pg_backup.config
    dest: /home/postgres/backups/pg_backup.config
    owner: postgres
    group: postgres
    mode: 0755

- name: Ensure pg_backup.sh
  template:
    src: home/postgres/backups/pg_backup.sh
    dest: /home/postgres/backups/pg_backup.sh
    owner: postgres
    group: postgres
    mode: 0755

- name: Ensure backup cron job
  cron:
    - name: "backup postgres db"
      minute: "0"
      hour: "3"
      special_time: daily
      job: "sudo -u postgres /home/postgres/backups/pg_backup.sh -c /home/postgres/backups/pg_config.sh"
